# DEBUG
/g4PSI/det/component Beamline
#/g4PSI/det/component Structure
# === beamline detectors === 
/g4PSI/det/component BHA
#/g4PSI/det/component BHC
#/g4PSI/det/component BHD
/g4PSI/det/component GEM0
/g4PSI/det/component GEM1
/g4PSI/det/component GEM2
/g4PSI/det/component GEM3
#/g4PSI/det/component VETO
#/g4PSI/det/component ScatteringChamber_TypeTrapezoid
#/g4PSI/det/component Target_TypeUMich
#/g4PSI/det/target_state full
#/g4PSI/det/component BM state = closed
#/g4PSI/det/component CAL
# === scattered particle detectors === 
/g4PSI/det/component SPSLF
/g4PSI/det/component SPSRF
/g4PSI/det/component SPSLR
/g4PSI/det/component SPSRR
/g4PSI/det/kapton_thickness 120 um
/g4PSI/det/target_radius 30 mm
/g4PSI/det/pipe_distance 60 mm
/g4PSI/det/pipe_angle 25 deg
/g4PSI/det/entrance_window_thickness 120 um
/g4PSI/det/setup standard2015
# TOF

/g4PSI/det/trans GEM0 $GEM0XOFF $GEM0YOFF $GEM0ZOFF mm
/g4PSI/det/trans GEM1 $GEM1XOFF $GEM1YOFF $GEM1ZOFF mm
/g4PSI/det/trans GEM2 $GEM2XOFF $GEM2YOFF $GEM2ZOFF mm
/g4PSI/det/trans GEM3 $GEM3XOFF $GEM3YOFF $GEM3ZOFF mm
/g4PSI/det/rot GEM0 $GEM0XrotOFF $GEM0YrotOFF $GEM0ZrotOFF deg
/g4PSI/det/rot GEM1 $GEM1XrotOFF $GEM1YrotOFF $GEM1ZrotOFF deg
/g4PSI/det/rot GEM2 $GEM2XrotOFF $GEM2YrotOFF $GEM2ZrotOFF deg
/g4PSI/det/rot GEM3 $GEM3XrotOFF $GEM3YrotOFF $GEM3ZrotOFF deg

/g4PSI/det/trans MUSEFrame $BeamLineDetectorsXOFF $BeamLineDetectorsYOFF $BeamLineDetectorsZOFF mm
/g4PSI/det/rot MUSEFrame $BeamLineDetectorsXrotOFF $BeamLineDetectorsYrotOFF $BeamLineDetectorsZrotOFF deg

#/g4PSI/det/trans BeamLineDetectors $BeamLineDetectorsXOFF $BeamLineDetectorsYOFF $BeamLineDetectorsZOFF mm
#/g4PSI/det/rot BeamLineDetectors $BeamLineDetectorsXrotOFF $BeamLineDetectorsYrotOFF $BeamLineDetectorsZrotOFF deg

